defaults:
  - run-hpatches-tests-default
  - /models@model: silk-vgg-frozen-best
  - _self_

model:
  device: "cuda:0"

transform:
  _target_: silk.transforms.abstract.Compose
  _args_:
    # send all tensors to model's device
    - _target_: silk.transforms.abstract.Map
      function:
        _target_: silk.transforms.tensor.ToDevice
        device: ${mode.model.device}
    # run model on batch
    - _target_: silk.transforms.abstract.MethodCall
      name: ["original_probs", "original_points", "original_desc", "original_normalized_descriptors"]
      self_: ${mode.model}
      method: "model_forward_flow"
      images: "@original_img"
      outputs: ["score", "sparse_positions", "sparse_descriptors", "normalized_descriptors"]
    # run model on batch
    - _target_: silk.transforms.abstract.MethodCall
      name: ["warped_probs", "warped_points", "warped_desc", "warped_normalized_descriptors"]
      self_: ${mode.model}
      method: "model_forward_flow"
      images: "@warped_img"
      outputs: ["score", "sparse_positions", "sparse_descriptors", "normalized_descriptors"]

    # shift positions
    - _target_: silk.transforms.abstract.Lambda
      name: "original_points"
      function:
        _target_: silk.config.core.locate
        path: silk.backbones.silk.silk.from_feature_coords_to_image_coords
      model: ${mode.model}
      desc_positions: "@original_points"

    - _target_: silk.transforms.abstract.Lambda
      name: "warped_points"
      function:
        _target_: silk.config.core.locate
        path: silk.backbones.silk.silk.from_feature_coords_to_image_coords
      model: ${mode.model}
      desc_positions: "@warped_points"

    # run matching
    - _target_: silk.transforms.abstract.Lambda
      name: ["estimated_homography", "matched_original_points", "matched_warped_points"]
      function:
        _target_: silk.config.core.locate
        path: silk.matching.mnn.batched_estimate_homography
      points_0: "@original_points"
      points_1: "@warped_points"
      desc_0: "@original_desc"
      desc_1: "@warped_desc"
      ordering: "yx"
      matcher_fn:
        _target_: silk.models.silk.matcher
        postprocessing: "none"
        # postprocessing: "ratio-test"
        # postprocessing: "double-softmax"
        # threshold: 0.8
        # temperature: 0.1
